package game

const ARCS_BG string = "arcs1.png"
const ARCS_FG string = "arcs2.png"
const DASHBOARD string = "dashboard.png"

const BANNERS string = "banners.png"
const BADGES string = "badges.png"
const LOCKED string = "locked_badge.png"
const AMULET string = "amulet.png"

const CHROME string = "chrome.png"
const ICONS string = "icons.png"
const STATUS string = "status_pane.png"
const HP_BAR string = "hp_bar.png"
const XP_BAR string = "exp_bar.png"
const TOOLBAR string = "toolbar.png"
const SHADOW string = "shadow.png"

const WARRIOR string = "warrior.png"
const MAGE string = "mage.png"
const ROGUE string = "rogue.png"
const HUNTRESS string = "ranger.png"
const AVATARS string = "avatars.png"
const PET string = "pet.png"

const SURFACE string = "surface.png"

const FIREBALL string = "fireball.png"
const SPECKS string = "specks.png"
const EFFECTS string = "effects.png"

const RAT string = "rat.png"
const GNOLL string = "gnoll.png"
const CRAB string = "crab.png"
const GOO string = "goo.png"
const SWARM string = "swarm.png"
const SKELETON string = "skeleton.png"
const SHAMAN string = "shaman.png"
const THIEF string = "thief.png"
const TENGU string = "tengu.png"
const SHEEP string = "sheep.png"
const KEEPER string = "shopkeeper.png"
const BAT string = "bat.png"
const BRUTE string = "brute.png"
const SPINNER string = "spinner.png"
const DM300 string = "dm300.png"
const WRAITH string = "wraith.png"
const ELEMENTAL string = "elemental.png"
const MONK string = "monk.png"
const WARLOCK string = "warlock.png"
const GOLEM string = "golem.png"
const UNDEAD string = "undead.png"
const KING string = "king.png"
const STATUE string = "statue.png"
const PIRANHA string = "piranha.png"
const EYE string = "eye.png"
const SUCCUBUS string = "succubus.png"
const SCORPIO string = "scorpio.png"
const ROTTING string = "rotting_fist.png"
const BURNING string = "burning_fist.png"
const YOG string = "yog.png"
const LARVA string = "larva.png"
const GHOST string = "ghost.png"
const MAKER string = "wandmaker.png"
const TROLL string = "blacksmith.png"
const IMP string = "demon.png"
const RATKING string = "ratking.png"
const BEE string = "bee.png"
const MIMIC string = "mimic.png"

const ITEMS string = "items.png"
const PLANTS string = "plants.png"

const TILES_SEWERS string = "tiles0.png"
const TILES_PRISON string = "tiles1.png"
const TILES_CAVES string = "tiles2.png"
const TILES_CITY string = "tiles3.png"
const TILES_HALLS string = "tiles4.png"

const WATER_SEWERS string = "water0.png"
const WATER_PRISON string = "water1.png"
const WATER_CAVES string = "water2.png"
const WATER_CITY string = "water3.png"
const WATER_HALLS string = "water4.png"

const BUFFS_SMALL string = "buffs.png"
const BUFFS_LARGE string = "large_buffs.png"
const SPELL_ICONS string = "spell_icons.png"

const FONTS1X string = "font1x.png"
const FONTS15X string = "font15x.png"
const FONTS2X string = "font2x.png"
const FONTS25X string = "font25x.png"
const FONTS3X string = "font3x.png"

const THEME string = "theme.mp3"
const TUNE string = "game.mp3"
const HAPPY string = "surface.mp3"

const SND_CLICK string = "snd_click.mp3"
const SND_BADGE string = "snd_badge.mp3"
const SND_GOLD string = "snd_gold.mp3"

const SND_OPEN string = "snd_door_open.mp3"
const SND_UNLOCK string = "snd_unlock.mp3"
const SND_ITEM string = "snd_item.mp3"
const SND_DEWDROP string = "snd_dewdrop.mp3"
const SND_HIT string = "snd_hit.mp3"
const SND_MISS string = "snd_miss.mp3"
const SND_STEP string = "snd_step.mp3"
const SND_WATER string = "snd_water.mp3"
const SND_DESCEND string = "snd_descend.mp3"
const SND_EAT string = "snd_eat.mp3"
const SND_READ string = "snd_read.mp3"
const SND_LULLABY string = "snd_lullaby.mp3"
const SND_DRINK string = "snd_drink.mp3"
const SND_SHATTER string = "snd_shatter.mp3"
const SND_ZAP string = "snd_zap.mp3"
const SND_LIGHTNING string = "snd_lightning.mp3"
const SND_LEVELUP string = "snd_levelup.mp3"
const SND_DEATH string = "snd_death.mp3"
const SND_CHALLENGE string = "snd_challenge.mp3"
const SND_CURSED string = "snd_cursed.mp3"
const SND_TRAP string = "snd_trap.mp3"
const SND_EVOKE string = "snd_evoke.mp3"
const SND_TOMB string = "snd_tomb.mp3"
const SND_ALERT string = "snd_alert.mp3"
const SND_MELD string = "snd_meld.mp3"
const SND_BOSS string = "snd_boss.mp3"
const SND_BLAST string = "snd_blast.mp3"
const SND_PLANT string = "snd_plant.mp3"
const SND_RAY string = "snd_ray.mp3"
const SND_BEACON string = "snd_beacon.mp3"
const SND_TELEPORT string = "snd_teleport.mp3"
const SND_CHARMS string = "snd_charms.mp3"
const SND_MASTERY string = "snd_mastery.mp3"
const SND_PUFF string = "snd_puff.mp3"
const SND_ROCKS string = "snd_rocks.mp3"
const SND_BURNING string = "snd_burning.mp3"
const SND_FALLING string = "snd_falling.mp3"
const SND_GHOST string = "snd_ghost.mp3"
const SND_SECRET string = "snd_secret.mp3"
const SND_BONES string = "snd_bones.mp3"
const SND_BEE string = "snd_bee.mp3"
const SND_DEGRADE string = "snd_degrade.mp3"
const SND_MIMIC string = "snd_mimic.mp3"
