package game

var AssetEffects map[string]string = map[string]string{
	"FIREBALL_TALL":  "effects/fireball-tall.png",
	"FIREBALL_SHORT": "effects/fireball-short.png",
	"SPECKS":         "effects/specks.png",
	"EFFECTS":        "effects/effects.png",
	"SPELL_ICONS":    "effects/spell_icons.png",
}

var AssetFonts map[string]string = map[string]string{
	"FONT_PIXEL": "fonts/pixel_font.png",
	"FONT_TTF":   "fonts/pixel_font.ttf",
}

var AssetInterface map[string]string = map[string]string{
	"ARCS_BG": "interfaces/arcs1.png",
	"ARCS_FG": "interfaces/arcs2.png",
	// "DASHBOARD": "dashboard.png",
	"BANNERS":     "interfaces/banners.png",
	"BADGES":      "interfaces/badges.png",
	"LOCKED":      "interfaces/locked_badge.png",
	"CHROME":      "interfaces/chrome.png",
	"ICONS":       "interfaces/icons.png",
	"STATUS":      "interfaces/status_pane.png",
	"TOOLBAR":     "interfaces/toolbar.png",
	"SHADOW":      "interfaces/shadow.png",
	"SURFACE":     "interfaces/surface.png",
	"BUFFS_SMALL": "interfaces/buffs.png",
	"BUFFS_LARGE": "interfaces/large_buffs.png",
}

var AssetMusic map[string]string = map[string]string{
	"THEME_1":      "music/theme_1.ogg",
	"THEME_2":      "music/theme_2.ogg",
	"THEME_FINALE": "music/theme_finale.ogg",
}

var AssetSounds map[string]string = map[string]string{
	"SND_GOLD":      "sounds/gold.mp3",
	"SND_OPEN":      "sounds/door_open.mp3",
	"SND_UNLOCK":    "sounds/unlock.mp3",
	"SND_ITEM":      "sounds/item.mp3",
	"SND_DEWDROP":   "sounds/dewdrop.mp3",
	"SND_HIT":       "sounds/hit.mp3",
	"SND_MISS":      "sounds/miss.mp3",
	"SND_STEP":      "sounds/step.mp3",
	"SND_WATER":     "sounds/water.mp3",
	"SND_DESCEND":   "sounds/descend.mp3",
	"SND_EAT":       "sounds/eat.mp3",
	"SND_READ":      "sounds/read.mp3",
	"SND_LULLABY":   "sounds/lullaby.mp3",
	"SND_DRINK":     "sounds/drink.mp3",
	"SND_SHATTER":   "sounds/shatter.mp3",
	"SND_ZAP":       "sounds/zap.mp3",
	"SND_LIGHTNING": "sounds/lightning.mp3",
	"SND_LEVELUP":   "sounds/levelup.mp3",
	"SND_DEATH":     "sounds/death.mp3",
	"SND_CHALLENGE": "sounds/challenge.mp3",
	"SND_CURSED":    "sounds/cursed.mp3",
	"SND_TRAP":      "sounds/trap.mp3",
	"SND_EVOKE":     "sounds/evoke.mp3",
	"SND_TOMB":      "sounds/tomb.mp3",
	"SND_ALERT":     "sounds/alert.mp3",
	"SND_MELD":      "sounds/meld.mp3",
	"SND_BOSS":      "sounds/boss.mp3",
	"SND_BLAST":     "sounds/blast.mp3",
	"SND_PLANT":     "sounds/plant.mp3",
	"SND_RAY":       "sounds/ray.mp3",
	"SND_BEACON":    "sounds/beacon.mp3",
	"SND_TELEPORT":  "sounds/teleport.mp3",
	"SND_CHARMS":    "sounds/charms.mp3",
	"SND_MASTERY":   "sounds/mastery.mp3",
	"SND_PUFF":      "sounds/puff.mp3",
	"SND_ROCKS":     "sounds/rocks.mp3",
	"SND_BURNING":   "sounds/burning.mp3",
	"SND_FALLING":   "sounds/falling.mp3",
	"SND_GHOST":     "sounds/ghost.mp3",
	"SND_SECRET":    "sounds/secret.mp3",
	"SND_BONES":     "sounds/bones.mp3",
	"SND_BEE":       "sounds/bee.mp3",
	"SND_DEGRADE":   "sounds/degrade.mp3",
	"SND_MIMIC":     "sounds/mimic.mp3",
}

var AssetSprites map[string]string = map[string]string{
	"AMULET":   "sprites/amulet.png",
	"WARRIOR":  "sprites/warrior.png",
	"MAGE":     "sprites/mage.png",
	"ROGUE":    "sprites/rogue.png",
	"HUNTRESS": "sprites/ranger.png",
	"AVATARS":  "sprites/avatars.png",
	"PET":      "sprites/pet.png",

	"RAT":       "sprites/rat.png",
	"GNOLL":     "sprites/gnoll.png",
	"CRAB":      "sprites/crab.png",
	"GOO":       "sprites/goo.png",
	"SWARM":     "sprites/swarm.png",
	"SKELETON":  "sprites/skeleton.png",
	"SHAMAN":    "sprites/shaman.png",
	"THIEF":     "sprites/thief.png",
	"TENGU":     "sprites/tengu.png",
	"SHEEP":     "sprites/sheep.png",
	"KEEPER":    "sprites/shopkeeper.png",
	"BAT":       "sprites/bat.png",
	"BRUTE":     "sprites/brute.png",
	"SPINNER":   "sprites/spinner.png",
	"DM300":     "sprites/dm300.png",
	"WRAITH":    "sprites/wraith.png",
	"ELEMENTAL": "sprites/elemental.png",
	"MONK":      "sprites/monk.png",
	"WARLOCK":   "sprites/warlock.png",
	"GOLEM":     "sprites/golem.png",
	"UNDEAD":    "sprites/undead.png",
	"KING":      "sprites/king.png",
	"STATUE":    "sprites/statue.png",
	"PIRANHA":   "sprites/piranha.png",
	"EYE":       "sprites/eye.png",
	"SUCCUBUS":  "sprites/succubus.png",
	"SCORPIO":   "sprites/scorpio.png",
	"ROTTING":   "sprites/rotting_fist.png",
	"BURNING":   "sprites/burning_fist.png",
	"YOG":       "sprites/yog.png",
	"LARVA":     "sprites/larva.png",
	"GHOST":     "sprites/ghost.png",
	"MAKER":     "sprites/wandmaker.png",
	"TROLL":     "sprites/blacksmith.png",
	"IMP":       "sprites/demon.png",
	"RATKING":   "sprites/ratking.png",
	"BEE":       "sprites/bee.png",
	"MIMIC":     "sprites/mimic.png",

	"ITEMS": "sprites/items.png",
}

var AssetTiles map[string]string = map[string]string{
	"TILES_SEWERS": "environment/tiles_sewers.png",
	"TILES_PRISON": "environment/tiles_prison.png",
	"TILES_CAVES":  "environment/tiles_caves.png",
	"TILES_CITY":   "environment/tiles_city.png",
	"TILES_HALLS":  "environment/tiles_halls.png",

	"WATER_SEWERS": "environment/water0.png",
	"WATER_PRISON": "environment/water1.png",
	"WATER_CAVES":  "environment/water2.png",
	"WATER_CITY":   "environment/water3.png",
	"WATER_HALLS":  "environment/water4.png",
}
